require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comissions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Comission. As you add validations to Comission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Comission.create! valid_attributes
      get comissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      comission = Comission.create! valid_attributes
      get comission_url(comission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_comission_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      comission = Comission.create! valid_attributes
      get edit_comission_url(comission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Comission" do
        expect {
          post comissions_url, params: { comission: valid_attributes }
        }.to change(Comission, :count).by(1)
      end

      it "redirects to the created comission" do
        post comissions_url, params: { comission: valid_attributes }
        expect(response).to redirect_to(comission_url(Comission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Comission" do
        expect {
          post comissions_url, params: { comission: invalid_attributes }
        }.to change(Comission, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post comissions_url, params: { comission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested comission" do
        comission = Comission.create! valid_attributes
        patch comission_url(comission), params: { comission: new_attributes }
        comission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the comission" do
        comission = Comission.create! valid_attributes
        patch comission_url(comission), params: { comission: new_attributes }
        comission.reload
        expect(response).to redirect_to(comission_url(comission))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        comission = Comission.create! valid_attributes
        patch comission_url(comission), params: { comission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested comission" do
      comission = Comission.create! valid_attributes
      expect {
        delete comission_url(comission)
      }.to change(Comission, :count).by(-1)
    end

    it "redirects to the comissions list" do
      comission = Comission.create! valid_attributes
      delete comission_url(comission)
      expect(response).to redirect_to(comissions_url)
    end
  end
end
